AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hella Rad

Globals:
  Function:
    Timeout: 10

Resources:
  ConductorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Conductor'
      CodeUri: conductor
      Handler: conductor
      Runtime: go1.x

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-Alert'
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt ConductorFunction.Arn

  ConductorInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ConductorFunction
      Principal: sns.amazonaws.com

  GreynoiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Greynoise'
      CodeUri: function/greynoise
      Handler: greynoise
      Runtime: go1.x

  IPAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-IPapi'
      CodeUri: function/ipapi
      Handler: ipapi
      Runtime: go1.x

  OutputFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Output'
      CodeUri: output/opsgenie
      Handler: opsgenie
      Runtime: go1.x

  IPLookupStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub '${AWS::StackName}-IPLookup'
      DefinitionUri: statemachine/ipLookup.asl.json
      DefinitionSubstitutions:
        GreynoiseFunctionArn: !GetAtt GreynoiseFunction.Arn
        IPAPIFunctionArn: !GetAtt IPAPIFunction.Arn
        OutputFunctionArn: !GetAtt OutputFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref GreynoiseFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref IPAPIFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref OutputFunction